services:

  postgres:
    image: postgres:15
    container_name: airport_postgres
    environment:
      POSTGRES_DB: airport_db
      POSTGRES_USER: airport
      POSTGRES_PASSWORD: airport
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: airport_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  integration-service:
    build: ./services/integration-service
    container_name: airport_integration
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq

  event-consumer:
    build: ./services/event-consumer
    container_name: airport_consumer
    depends_on:
      - postgres
      - rabbitmq
